### ISSUE TITLE
Add `swapStatus(uint swapNumber)`  function to RestrictedSwap.sol

### ISSUE THREAD

**Issue by aquabu** [CoMakery/comakery-security-token#44]
Scenario: as an observer of the swap, I want to be able to know if the swap is configured, complete or canceled

When I get the swapNumber from the SwapConfigured event
And I call  `restrictedSwap.swapStatus(swapNumber)`
Then I should get the correct enum status

Acceptance:
* Implement `restrictedSwap.swapStatus()`
* Unit tests verifying all the correct states are returned

**Comment by Denis-Davidoff** [comment]
Do I need to check access use onlyWalletsAdminOrReserveAdmin modificator or another?
What visibility of function required: external or public? I'm using external.

**Comment by aquabu** [comment]
@Denis-Davidoff this should be callable by anyone. I think `external` is good because the function isn't referenced internally.
